--------------------------------------------------------
--  Fichier créé - dimanche-décembre-04-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AFFJURIDIQUE
--------------------------------------------------------

  CREATE TABLE  "AFFJURIDIQUE" 
   (	"NUMDOSSIER" NUMBER, 
	"ETATDOSSIER" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"DECISIONDOSSIER" VARCHAR2(20 BYTE), 
	"NOMACCUSE" VARCHAR2(20 BYTE), 
	"PRENOMACCUSE" VARCHAR2(20 BYTE), 
	"DATENAISSANCE" VARCHAR2(20 BYTE), 
	"EMPRETE" VARCHAR2(20 BYTE), 
	"IDAVOCAT" NUMBER, 
	"ARCHIVE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE    ;
--------------------------------------------------------
--  DDL for Table AUDIENCES
--------------------------------------------------------

  CREATE TABLE  "AUDIENCES" 
   (	"NUM_AUD" NUMBER, 
	"SALLE" NUMBER, 
	"DUREE" NUMBER, 
	"DATE_A" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE    ;
--------------------------------------------------------
--  DDL for Table HISTORIQUE
--------------------------------------------------------

  CREATE TABLE  "HISTORIQUE" 
   (	"NUM_AUD" NUMBER, 
	"DATE_H" DATE, 
	"OPERATION" VARCHAR2(20 BYTE), 
	"ID_H" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE    ;
--------------------------------------------------------
--  DDL for Table SALLE
--------------------------------------------------------

  CREATE TABLE  "SALLE" 
   (	"NUMSALLE" NUMBER, 
	"ETAGE" NUMBER, 
	"CAPACITER" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE    ;
--------------------------------------------------------
--  DDL for Table PERSO
--------------------------------------------------------

  CREATE TABLE  "PERSO" 
   (	"NOMPRENOM" VARCHAR2(20 BYTE), 
	"CIN" VARCHAR2(20 BYTE), 
	"NUM" VARCHAR2(20 BYTE), 
	"ADR" VARCHAR2(20 BYTE), 
	"POSTE" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE    ;
REM INSERTING into SYSTEM.AFFJURIDIQUE
SET DEFINE OFF;
Insert into SYSTEM.AFFJURIDIQUE (NUMDOSSIER,ETATDOSSIER,TYPE,DECISIONDOSSIER,NOMACCUSE,PRENOMACCUSE,DATENAISSANCE,EMPRETE,IDAVOCAT,ARCHIVE) values ('2','Fini','Divorce','aa','aze','aze','01/01/2000','aze','1','0');
REM INSERTING into SYSTEM.AUDIENCES
SET DEFINE OFF;
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('6','1','2',to_date('01/01/00','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('29','5','4',to_date('04/04/18','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('22','4','1',to_date('20/11/22','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('27','5','1',to_date('01/07/18','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('8','1','1',to_date('22/01/99','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('9','1','2',to_date('06/01/01','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('10','1','4',to_date('07/01/00','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('23','4','2',to_date('13/02/21','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('12','2','8',to_date('14/11/22','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('13','2','4',to_date('15/11/22','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('14','2','8',to_date('13/11/22','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('15','2','4',to_date('12/11/22','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('16','3','2',to_date('16/11/22','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('17','3','1',to_date('05/05/21','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('18','3','2',to_date('18/12/18','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('19','3','3',to_date('14/04/01','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('20','3','3',to_date('23/07/02','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('21','4','4',to_date('19/11/22','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('24','4','1',to_date('27/11/22','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('28','5','1',to_date('14/07/18','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('26','5','2',to_date('22/11/21','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('30','5','5',to_date('03/04/18','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('31','5','1',to_date('03/05/18','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('41','1','3',to_date('01/01/00','DD/MM/RR'));
Insert into SYSTEM.AUDIENCES (NUM_AUD,SALLE,DUREE,DATE_A) values ('42','28','4',to_date('01/01/00','DD/MM/RR'));
REM INSERTING into SYSTEM.HISTORIQUE
SET DEFINE OFF;
Insert into SYSTEM.HISTORIQUE (NUM_AUD,DATE_H,OPERATION,ID_H) values ('5',to_date('14/11/22','DD/MM/RR'),'Suppression','1');
Insert into SYSTEM.HISTORIQUE (NUM_AUD,DATE_H,OPERATION,ID_H) values ('6',to_date('14/11/22','DD/MM/RR'),'Modifier','2');
Insert into SYSTEM.HISTORIQUE (NUM_AUD,DATE_H,OPERATION,ID_H) values ('9',to_date('14/11/22','DD/MM/RR'),'Modifier','3');
Insert into SYSTEM.HISTORIQUE (NUM_AUD,DATE_H,OPERATION,ID_H) values ('7',to_date('14/11/22','DD/MM/RR'),'Suppression','4');
Insert into SYSTEM.HISTORIQUE (NUM_AUD,DATE_H,OPERATION,ID_H) values ('6',to_date('04/12/22','DD/MM/RR'),'Modifier','21');
REM INSERTING into SYSTEM.SALLE
SET DEFINE OFF;
Insert into SYSTEM.SALLE (NUMSALLE,ETAGE,CAPACITER,TYPE,ETAT) values ('1','0','50','aze','aze');
Insert into SYSTEM.SALLE (NUMSALLE,ETAGE,CAPACITER,TYPE,ETAT) values ('2','0','0','buvette',null);
REM INSERTING into SYSTEM.PERSO
SET DEFINE OFF;
Insert into SYSTEM.PERSO (NOMPRENOM,CIN,NUM,ADR,POSTE) values ('bbbb','1425','14257','azeaze','azeaze');
--------------------------------------------------------
--  DDL for Index AFFJURIDIQUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX  "AFFJURIDIQUE_PK" ON  "AFFJURIDIQUE" ("NUMDOSSIER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE    ;
--------------------------------------------------------
--  DDL for Index SEQUENCE_NUM
--------------------------------------------------------

  CREATE UNIQUE INDEX  "SEQUENCE_NUM" ON  "AUDIENCES" ("NUM_AUD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE    ;
--------------------------------------------------------
--  DDL for Index HISTORIQUE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX  "HISTORIQUE_PK" ON  "HISTORIQUE" ("ID_H") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE    ;
--------------------------------------------------------
--  DDL for Index SALLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX  "SALLE_PK" ON  "SALLE" ("NUMSALLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE    ;
--------------------------------------------------------
--  DDL for Trigger AUDIENCES_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER  "AUDIENCES_TRG" 
BEFORE INSERT ON AUDIENCES 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NUM_AUD IS NULL THEN
      SELECT AUDIENCES_SEQ.NEXTVAL INTO :NEW.NUM_AUD FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER  "AUDIENCES_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table AFFJURIDIQUE
--------------------------------------------------------

  ALTER TABLE  "AFFJURIDIQUE" ADD CONSTRAINT "AFFJURIDIQUE_PK" PRIMARY KEY ("NUMDOSSIER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE     ENABLE;
  ALTER TABLE  "AFFJURIDIQUE" MODIFY ("NUMDOSSIER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUDIENCES
--------------------------------------------------------

  ALTER TABLE  "AUDIENCES" ADD CONSTRAINT "TAB_DES_AUDIENCES_PK" PRIMARY KEY ("NUM_AUD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE     ENABLE;
  ALTER TABLE  "AUDIENCES" MODIFY ("DUREE" NOT NULL ENABLE);
  ALTER TABLE  "AUDIENCES" MODIFY ("SALLE" NOT NULL ENABLE);
  ALTER TABLE  "AUDIENCES" MODIFY ("NUM_AUD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORIQUE
--------------------------------------------------------

  ALTER TABLE  "HISTORIQUE" ADD CONSTRAINT "HISTORIQUE_PK" PRIMARY KEY ("ID_H")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE     ENABLE;
  ALTER TABLE  "HISTORIQUE" MODIFY ("DATE_H" NOT NULL ENABLE);
  ALTER TABLE  "HISTORIQUE" MODIFY ("ID_H" NOT NULL ENABLE);
  ALTER TABLE  "HISTORIQUE" MODIFY ("OPERATION" NOT NULL ENABLE);
  ALTER TABLE  "HISTORIQUE" MODIFY ("NUM_AUD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SALLE
--------------------------------------------------------

  ALTER TABLE  "SALLE" ADD CONSTRAINT "SALLE_PK" PRIMARY KEY ("NUMSALLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE     ENABLE;
  ALTER TABLE  "SALLE" MODIFY ("NUMSALLE" NOT NULL ENABLE);
